service_out_of_memes:
  en: |-
    🚀 You've watched all the memes we've prepared for you! Come back tomorrow for MORE. 🍔
  ru: |-
    🚀 Ты посмотрел все мемы, которые мы подготовили для тебя! Приходи завтра, покажем ЕЩЕ. 🍔
  uk: |-
    🚀 Ти переглянув всі меми, які ми підготували для тебе! Приходь завтра, покажемо БІЛЬШЕ. 🍔
  ar: |-
    🚀 شاهدت جميع الصور المضحكة التي قمنا بتحضيرها لك! عد غدًا للمزيد. 🍔
  es: |-
    🚀 ¡Has visto todos los memes que hemos preparado para ti! Vuelve mañana para MÁS. 🍔
  pt: |-
    🚀 Você viu todos os memes que preparamos para você! Volte amanhã para MAIS. 🍔
  fr: |-
    🚀 Tu as regardé tous les memes que nous avons préparés pour toi! Reviens demain pour PLUS. 🍔
  de: |-
    🚀 Du hast alle Memes gesehen, die wir für dich vorbereitet haben! Komm morgen wieder für MEHR. 🍔
  it: |-
    🚀 Hai visto tutti i meme che abbiamo preparato per te! Torna domani per ALTRO. 🍔
  pl: |-
    🚀 Obejrzałeś wszystkie memy, które dla ciebie przygotowaliśmy! Wróć jutro po WIĘCEJ. 🍔
